name: CD

on:
  workflow_dispatch:

jobs:
  #Docker
  Docker:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_tag.outputs.latest_tag }}
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

        # Login into DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Get latest semver tag from DockerHub
      - name: Get semver tag
        id: get_tag
        run: |
          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ secrets.DOCKER_USERNAME }}/devops:pull" | jq -r .token)

          LATEST_TAG=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://registry-1.docker.io/v2/${{ secrets.DOCKER_USERNAME }}/devops/tags/list" \
            | jq -r '.tags[]' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -Vr \
            | head -n1)

          echo "Latest semver tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

  Deployment:
    runs-on: ubuntu-latest
    needs: Docker
    steps:
      # Pull latest Docker image
      - name: Pull Docker image
        run: |
          echo "Pulling image: ${{ secrets.DOCKER_USERNAME }}/devops:${{ needs.Docker.outputs.latest_tag }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops:${{ needs.Docker.outputs.latest_tag }}

      # Deploy latest Docker image
      - name: Run container
        run: |
          echo "Deploying Interactive Calculator Application ..."
          docker run -d --name calc_api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/devops:${{ needs.Docker.outputs.latest_tag }}

      # Run tests via curl
      - name: Run tests via curl
        run: |
          echo "Running tests against the deployed application:"
          sleep 5
          echo "Test: a = 10; b = 10"
          echo "Addition:       $(curl -s 'http://localhost:8080/api/calculator/calculate?a=10&b=10&operation=%2B')"
          echo "Subtraction:    $(curl -s 'http://localhost:8080/api/calculator/calculate?a=10&b=10&operation=-')"
          echo "Multiplication: $(curl -s 'http://localhost:8080/api/calculator/calculate?a=10&b=10&operation=*')"
          echo "Division:       $(curl -s 'http://localhost:8080/api/calculator/calculate?a=10&b=10&operation=/')"
          echo ""
          echo "Test: a = 9; b = 3"
          echo "Addition:       $(curl -s 'http://localhost:8080/api/calculator/calculate?a=9&b=3&operation=%2B')"
          echo "Subtraction:    $(curl -s 'http://localhost:8080/api/calculator/calculate?a=9&b=3&operation=-')"
          echo "Multiplication: $(curl -s 'http://localhost:8080/api/calculator/calculate?a=9&b=3&operation=*')"
          echo "Division:       $(curl -s 'http://localhost:8080/api/calculator/calculate?a=9&b=3&operation=/')"
          echo ""
          echo "Test: a = 15; b = 5"
          echo "Addition:       $(curl -s 'http://localhost:8080/api/calculator/calculate?a=15&b=5&operation=%2B')"
          echo "Subtraction:    $(curl -s 'http://localhost:8080/api/calculator/calculate?a=15&b=5&operation=-')"
          echo "Multiplication: $(curl -s 'http://localhost:8080/api/calculator/calculate?a=15&b=5&operation=*')"
          echo "Division:       $(curl -s 'http://localhost:8080/api/calculator/calculate?a=15&b=5&operation=/')"

  CleanUp:
    runs-on: ubuntu-latest
    needs: Deployment
    steps:
      # Shutdown Docker
      - name: Shutdown Docker
        run: |
          docker stop calc_api || true
          docker rm calc_api || true

      # Cleanup Docker images
      - name: Cleanup Docker images
        run: |
          echo "Cleaning up Docker images:"
          docker rmi ${{ secrets.DOCKER_USERNAME }}/devops:${{ needs.Docker.outputs.latest_tag }} || true

      # Docker logout 
      - name: Docker Logout
        run: docker logout
