name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest semver tag from DockerHub
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/devops/tags?page_size=100" \
            | jq -r '.results[].name' \
            | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -Vr \
            | head -n1)
          echo "Found latest tag: $LATEST_TAG"
          if [ -z "$LATEST_TAG" ]; then
            echo "No valid semver tag found. Exiting."
            exit 1
          fi
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Pull latest Docker image
        run: |
          echo "Pulling image: ${{ secrets.DOCKER_USERNAME }}/devops:${{ steps.get_latest_tag.outputs.latest_tag }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops:${{ steps.get_latest_tag.outputs.latest_tag }}

      - name: Deploy Interactive Calculator
        run: |
          echo "Deploying Interactive Calculator Application ..."
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/devops:${{ steps.get_latest_tag.outputs.latest_tag }}"
          echo ""
          echo "Calculator application successfully deployed!"
          echo ""
          echo "This calculator requires interactive terminal input and supports:"
          echo "   - Addition (+)"
          echo "   - Subtraction (-)"
          echo "   - Multiplication (*)"
          echo "   - Division (/)"
          echo ""

      - name: Run Calculator API in Docker
        run: |
          docker run -d -p 8080:8080 --name calc_api ${{ secrets.DOCKER_USERNAME }}/devops:${{ steps.get_latest_tag.outputs.latest_tag }}
          sleep 5
          echo "Addition:       $(curl -s 'http://localhost:8080/calculate?num1=5&num2=3&op=+')"
          echo "Subtraction:    $(curl -s 'http://localhost:8080/calculate?num1=10&num2=4&op=-')"
          echo "Multiplication: $(curl -s 'http://localhost:8080/calculate?num1=6&num2=7&op=*')"
          echo "Division:       $(curl -s 'http://localhost:8080/calculate?num1=20&num2=5&op=/')"
          docker stop calc_api
          docker rm calc_api
