name: Docker-CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Docker Login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Image pull
      - name: Pull Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}

      # Docker Container start
      - name: Run Docker Container
        run: |
          docker run -d --name devops-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
