name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        working-directory: ./DevOpsCalc
        run: mvn -B package
      - name: Junit Test Dashboard
        uses: janisz/action@v2
        with:
          paths: target/surefire-reports/*.xml
          output: test-results.md
          show: all
